In [39]:
import pandas as pd
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [49]:
cd=pd.read_csv("cars1.csv")

In [50]:
cd.head()

,konum,fiyat,marka,seri,model,yil,kilometre,vites_tipi,yakit_tipi,kasa_tipi,motor_hacmi,motor_gucu,cekis,ortalama_yakit_tuketimi,yakit_deposu,tramer,degisen,boyali
0,Adana,1169000.0,Renault,Megane,1.3 TCe Joy Comfort,2022,124000.0,Otomatik,Benzin,Sedan,1201.0,126.0,Önden Çekiş,5.3,50.0,71300.0,1,0
1,Adana,1520000.0,Skoda,Octavia,1.0 e-Tec Elite,2022,99000.0,Otomatik,Hibrit,Sedan,1201.0,101.0,Önden Çekiş,4.3,48.0,56060.0,0,1
2,Adana,469999.0,Peugeot,207,1.4 Trendy,2009,207500.0,Düz,LPG & Benzin,Hatchback/5,1360.0,91.0,Önden Çekiş,6.3,50.0,0.0,0,0
3,Adana,1150000.0,Audi,A4,A4 Sedan 2.0 TDI Quattro,2013,219000.0,Otomatik,Dizel,Sedan,1801.0,176.0,4WD (Sürekli),5.1,63.0,0.0,1,4
4,Adana,1430000.0,Toyota,Corolla,1.5 Dream,2021,63000.0,Otomatik,Benzin,Sedan,1490.0,125.0,Önden Çekiş,5.8,50.0,0.0,0,0

In [51]:
X = cd[["konum","marka","seri","model","yil","kilometre","vites_tipi","yakit_tipi","kasa_tipi","motor_hacmi","motor_gucu","cekis","ortalama_yakit_tuketimi","yakit_deposu","tramer","degisen","boyali"]]

y = cd["fiyat"]

In [52]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=15)

In [53]:
kategori=["konum","marka","seri","model","yil","vites_tipi","yakit_tipi","kasa_tipi","cekis"]

model = CatBoostRegressor(cat_features=kategori, verbose=0)
model.fit(X_train, y_train)

model.save_model("araba_fiyat_model.cbm")

In [54]:
y_pred = model.predict(X_test)

In [31]:
X_test

,konum,marka,seri,model,yil,kilometre,vites_tipi,yakit_tipi,kasa_tipi,motor_hacmi,motor_gucu,cekis,ortalama_yakit_tuketimi,yakit_deposu,tramer,degisen,boyali
16599,Giresun,Renault,Symbol,1.5 dCi Joy,2015,361000.0,Düz,Dizel,Sedan,1461.0,90.0,Önden Çekiş,3.9,50.0,0.0,2,8
34808,Sivas,Chevrolet,Aveo,1.2 LS,2010,158000.0,Düz,LPG & Benzin,Sedan,1206.0,84.0,Önden Çekiş,5.5,45.0,0.0,0,4
12218,Edirne,Renault,Megane,2.0 RXT,2000,329000.0,Düz,LPG & Benzin,Sedan,1998.0,115.0,Önden Çekiş,8.4,60.0,0.0,0,2
25647,Kütahya,Renault,Clio,1.5 dCi Grandtour Authentique,2011,206000.0,Düz,Dizel,Station wagon,1461.0,65.0,Önden Çekiş,4.5,55.0,0.0,0,0
49026,Ağrı,Volkswagen,Passat,1.4 TSi BlueMotion Comfortline,2018,78000.0,Düz,Benzin,Sedan,1395.0,125.0,Önden Çekiş,5.3,66.0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52298,Aydın,Toyota,Avensis,1.6 Comfort,2008,330000.0,Düz,LPG & Benzin,Sedan,1598.0,110.0,Önden Çekiş,7.2,60.0,0.0,0,0
4610,Antalya,Ford,Focus,1.6 TDCi Collection,2010,217000.0,Düz,Dizel,Hatchback/5,1560.0,90.0,Önden Çekiş,4.7,55.0,0.0,0,0
38458,Uşak,Renault,Fluence,1.5 dCi Dynamique,2011,315000.0,Düz,Dizel,Sedan,1461.0,85.0,Önden Çekiş,4.5,60.0,0.0,0,1
4293,Antalya,Ford,Fiesta,1.5 TDCi Trend X,2015,182000.0,Düz,Dizel,Hatchback/5,1401.0,51.0,Önden Çekiş,3.7,42.0,0.0,0,0
12173,Edirne,Hyundai,i20,1.0 T-GDI Style,2024,13000.0,Otomatik,Benzin,Hatchback/5,1200.0,76.0,Önden Çekiş,6.1,40.0,0.0,0,0

In [57]:
r2_score(y_test,y_pred)

0.964602513630548

In [32]:
y_test

16599     398000.0
34808     350000.0
12218     320000.0
25647     515000.0
49026    1660000.0
           ...
52298     470000.0
4610      678000.0
38458     470000.0
4293      699000.0
12173    1352950.0
Name: fiyat, Length: 10812, dtype: float64

In [36]:
y_pred

array([ 263431.64610237,  462841.42204976,  304028.74859804, ...,
        428767.63104433,  761088.09888694, 1238697.23423507],
      shape=(10812,))

In [55]:
import numpy as np
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100

In [56]:
mape

np.float64(9.39376504994987)